### ISSUE TITLE
Issue with the rewrite_as_lambda(value)

### ISSUE THREAD

**Issue by setare92-ha** [learn-co-curriculum/dsc-lambda-functions-lab#2]
## Issue Subtype

- [ x] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```
Create a new column 'Review_Length' by applying this lambda function to the 'Review_num_words' column.
def rewrite_as_lambda(value):
    if len(value) < 50:
        return 'Short'
    elif len(value) < 80:
        return 'Medium'
    else:
        return 'Long'
```

### Concern

The Review_num_words column contains data of integer type since it's just the length of review text. Using the following lambda function will throw an error since an object of type int does not have len(). Removing len() from the function and keeping everything else the same will resolve the issue. 

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Thank you for letting us know. We'll take a look.

**Comment by bpurdy-ds** [comment]
It ran fine for us. If you are still having issues, please reach out to your instructor.

**Comment by setare92-ha** [comment]
> It ran fine for us. If you are still having issues, please reach out to your instructor.

Thanks for checking. Yes, the code runs fine simply because the function mentioned is not being used in the solution (its rewritten version is used in the form of a lambda function). What I'm pointing out is the following: the input to this function is the "value" variable, which has type "int". If you were to use the function in a piece of code, the function will inevitably throw an error because a variable of type "int" does not have len.
